# COOKIES POLICY

Before you start browsing, we inform you that we use cookies with different purposes on the web https://cgs.vote, so that you can decide if you want them installed on your computer or not.

If you continue browsing at https://cgs.vote, ICOFUNDING S.L. (hereinafter, ICOFUNDING) will deduct that you accept the installation of the cookies, and that you give the consent to be able to install them on your computer.

## WHAT ARE THE COOKIES?

Cookies are small information files that are sent and stored on the computer from which you access to the web https://cgs.vote (PC or personal computer, mobile phone, tablet, connected TV, etc.) making it easier to use of the same, to offer a better service.

The Web https://cgs.vote uses both own and third-party cookies that help us improve quality, allowing us to compare, remember, control and understand how our users navigate through the Web, identifying what they find useful and what not; and thus be able to improve the navigation process.

The cookies that use the Site do not damage your equipment, they only serve to improve the offered services. Some are strictly necessary for the page to work well (technical and personalization) and others serve to improve performance and user experience (analysis, advertising and behavioral advertising).

The Web uses both session cookies, temporary cookies, and permanent cookies. Session cookies store data while the user accesses the Web and expires when the browser is closed; while the permanent cookies store the data in the terminal to be accessed and used in more than one session. These last ones usually expire when a period of time exists that can oscillate between the two months and the two years.

## COOKIES DEACTIVATION

You have the option to allow, block or delete cookies installed on your computer by configuring the browser options installed on your computer. When you disable cookies, some of the available services may stop working. The way to disable cookies is different for each browser, but can usually be done from the Tools or Options menu.

You can also consult the Help menu of the browser where you can find instructions. The user may - at any time - choose which cookies he wants to work on this website through the browser configuration; for example:

* Microsoft Internet Explorer
* Mozilla Firefox
* Chrome
* Safari
* Opera

## TYPES OF COOKIES

Depending on the purpose for which the data obtained through cookies are processed, the Web may use:

* **Technical cookies**: are those that allow the user to navigate through a web page, platform or application, and the use of different options or services that exist in it, such as traffic control and communicate data, identify the session and access restricted access parts.

* **Personalization cookies**: are those that allow the user to access the service with some general characteristics predefined according to a series of criteria in the user's terminal such as the language, the type of browser.

* **Analysis cookies**: are those that allow the monitoring and analysis of the behavior of users of the websites to which they are linked. The information collected through this type of cookies is used in the measurement of the activity of the websites, application or platform and for the elaboration of user navigation profiles.

* **Advertising Cookies**: are those that allow the management, in the most effective way possible, of advertising spaces.

* **Behavioral Advertising Cookies**: These cookies store information on the behavior of users obtained through the continuous observation of their browsing habits, which allows the development of a specific profile to show advertising based on it.

* **External Social Networking Cookies**: used to allow visitors to interact with content from different social platforms (facebook, youtube, twitter, linkedIn, etc.) and are generated only for users of said social networks. The conditions of use of these cookies and the information collected is regulated by the privacy policy of the corresponding social platform.

Currently the WEB uses the following types of cookies:

### OWN COOKIES

#### Technical Cookies

They manage the correct navigation through the Web and its contents, allowing to identify user sessions and to protect their use.

*Opt-out*: N/A

#### Customization Cookies

They improve the user experience by storing custom variables such as language or navigation preferences.

*Opt-out*: N/A

### THIRD PARTY COOKIES

#### Analysis Cookies 

*Google Analytics*: The Web uses Google Analytics, a web analytics service provided by Google, Inc., a Delaware company whose head office is at 1600 Amphitheater Parkway, Mountain View (California), CA 94043, United States ("Google "). The information generated by the cookie about your use of the Web (including your IP address) will be directly transmitted and stored by Google on servers in the United States. Google will use this information on behalf of EMPRESA in order to keep track of its use of the Web, compiling activity reports and providing other services related to Internet activity and use. Google will not associate your IP address with any other data available to Google.

*Opt-out*: https://tools.google.com/dlpage/gaoptout

#### External Social Network Cookies

**Youtube**

You Tube provides buttons and other features so you can share links to our website. Information sent outside the EU to You Tube is used by You Tube in accordance with its privacy policies.

*Opt-out*: http://www.google.com/intl/es/policies/technologies/types/

**Google Plus**

Google Plus provides buttons and other features so you can share links to our website. Information sent outside the EU to Google Plus is used by Google Plus in accordance with its privacy policies.
*Opt-out*: http://www.google.com/intl/es/policies/technologies/types/

**Facebook**

Facebook provides buttons and other features so you can share links to our website on your profile. Information sent outside the EU to Facebook, concerning the pages you have visited or about the things that interest you, is used by Facebook according to its privacy policies.

*Opt-out*: https://www.facebook.com/help/cookies/

**Twitter**

Twitter provides buttons and other features so you can share links to our website. The information sent outside the EU to Twitter is used by Twitter according to its privacy policies.

*Opt-out*: https://twitter.com/privacy?lang=es

**LinkedIn**

LinkedIn provides buttons and other features so you can share links to our Web in your profile. Information sent outside the EU to LinkedIn, regarding the pages you have visited or about the things that interest you is used according to your privacy policies.

*Opt-out*:https://www.linkedin.com/legal/cookie-policy?trk=hb_ft_cookie

The specific opt-out systems indicated in the table above regarding the cookie in question (these systems can cause a rejection cookie to be installed on your computer for your opt-out choice to work); or other third-party tools, available online, that allow users to detect cookies on each Web site they visit and manage their deactivation.

ICOFUNDING is not responsible for the content and veracity of the privacy policies of the third parties included in this cookie policy.

If you have any questions or concerns about this cookie policy, you may contact ICOFUNDING at info@icofunding.com
